### ISSUE TITLE
Question: OneOf json schemas

### ISSUE THREAD

**Issue by justman00** [chrusty/protoc-gen-jsonschema#102]
I have a question regarding the limitations of `protoc-gen-jsonschema` or `protobuf` as a whole.

Basically I intend to write a proto file that could generate a structure similar to this:
```json
{
    "description" : "schema validating people and vehicles",
    "type" : "object",
    "oneOf" : [
       {
        "type" : "object",
        "properties" : {
            "firstName" : {
                "type" : "string"
            },
            "lastName" : {
                "type" : "string"
            },
            "sport" : {
                "type" : "string"
            }
          }
      }, 
      {
        "type" : "object",
        "properties" : {
            "vehicle" : {
                "type" : "string"
            },
            "price" : {
                "type" : "integer"
            }
        },
        "additionalProperties":false
     }
    ]
}
```

Because if I try to create a similar thing in proto:
```protobuf
message SomeMessage {
    oneof oneof_type {
        TypeOne foo = 1;
        TypeTwo bar = 2;
    }
}

```

The generated json schema results into:
```json
{
  "properties": {
    "foo": {
        // properties inside
    },
    "bar": {
        // properties inside
    }
  }
}
```
which to be fair isn't the same as having a true oneOf that doesn't depend on the keys.

**Comment by chrusty** [comment]
Hi @justman00, thanks for raising this. Sorry I didn't get back to you sooner.

I'll take a look at this over the coming days and see if I can find an example that works for you.

**Comment by chrusty** [comment]
Hey @justman00, I've been looking into this and I have come to the conclusion that what is possible in JSONSchema doesn't always make sense when applied to proto. According to [this page](https://developers.google.com/protocol-buffers/docs/proto#oneof) `oneOf` in proto refers to a _field_ (not an entire message / object), so I guess they will always be nested in this way.

I wonder if it is somehow possible to stretch this. I'll think some more.

**Comment by justman00** [comment]
unfortunate, but thanks a lot for taking a look! 🙏
