### ISSUE TITLE
Support of optional fields in proto3

### ISSUE THREAD

**Issue by pfedan** [chrusty/protoc-gen-jsonschema#103]
I am stuck using protoc-gen-jsonschema with optional fields. Here's a minimal example:
```
syntax = "proto3";

package myPackage;

message myMessage {
    optional float myFloat = 1.0;
}
```
When compiling this file using ```protoc --jsonschema_out...``` (protobuf-compiler 3.19.1), it tells:
```
$ protoc --jsonschema_out=. --proto_path=src src/minimalOptional.proto 
minimalOptional.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-jsonschema hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--jsonschema_out: 
$ 
``` 
So here I am :).

Are there any plans on supporting optional fields in proto3? See also: [Protobuf v3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0)

**Comment by chrusty** [comment]
Hi @pfedan, thanks for raising this issue.

This is a weird one, given than fields in proto3 are _always_ optional! I started reading about this new feature after being notified of the issue you raised, and it seems that might be more about code generation than schemas and validation.

What is the effect for you at the moment. Are you able to generate your jsonschemas, or does it abort? It might be that I just have to update to a newer version of the proto package and this error/warning will go away. Or is there some actual converter behaviour which is missing as well?

Anyway I'll take a look at update you soon, and thanks for your interest in the project!

**Comment by chrusty** [comment]
I've got a PR here if you want to test it out (you'd have to build from this branch): https://github.com/chrusty/protoc-gen-jsonschema/pull/104

Let me do some further reading to see what else I might need to do to actually "support" optional proto3 fields.

**Comment by pfedan** [comment]
Hi @chrusty, I just built from your PR branch and now it works as desired. Thank you very much for your quick reaction!

We're using protocol buffers across a number of languages, and we find the optional declaration useful for documentation purposes - even though it is known, that actually every field is optional since proto3.

**Comment by chrusty** [comment]
OK I'll merge this as-is so you can get up and running, but will probably need to revisit the logic later on.

**Comment by chrusty** [comment]
Thanks again for raising this @pfedan. Here is a new release with the proto3 optional support flag enabled: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.3.4
