### ISSUE TITLE
Adding titles to generated JSON Schema

### ISSUE THREAD

**Issue by mrozycki-tink** [chrusty/protoc-gen-jsonschema#108]
I would be happy to implement it myself, but it seems like a bigger change, so I wanted to consult first.

Our main use-case for the JSON Schema is generating a form, which can then be filled out by users. Something like this: https://rjsf-team.github.io/react-jsonschema-form/. This means every field has a title and a description to explain what the thing is.

Descriptions are already handled by this generator, but the titles are not. Right now we're trying to auto-generate these from field names, which works well 90% of the time, but can look wonky, e.g. when the name contains an acronym. So it would be great if there was a way to include the title in the proto and have it included appropriately in the schema.

What I was thinking was something like this:

```proto
// Thing
//
// This is a thing.
message Thing {
  ...
}
```

If the comment has a line separated by an empty comment line, it could be split into title (the first line) and description (the rest of it). Otherwise just use the whole thing as a description like it is now. So the above would generate:

```JSON
{
  "Thing": {
    "title": "Thing",
    "description": "This is a thing.",
    ...
  },
  ...
}

**Comment by jcchavezs** [comment]
Just quick comment, libraries like `envoy` use something called `[:protodoc-title]` https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/bootstrap/v3/bootstrap.proto#L38

**Comment by chrusty** [comment]
Hello @mrozycki-tink and @jcchavezs, thanks for raising this. Sorry I've not been on it very quickly, had some other work going on in the background.

I'll see what I can make of this over the next few days.

Thanks for your interest in the project!

**Comment by chrusty** [comment]
The easiest thing for me to implement is this: https://github.com/protocolbuffers/protobuf-go/blob/master/types/descriptorpb/descriptor.pb.go#L2857

It looks like it is essentially as you suggest @mrozycki-tink. I'll try it out.

**Comment by chrusty** [comment]
I've got a PR for this: https://github.com/chrusty/protoc-gen-jsonschema/pull/110

@mrozycki-tink do you want to try this branch out before I merge? Let me know if this does what you want.

**Comment by jcchavezs** [comment]
I was looking at other proto files to understand what they use in general and verify whether this approach makes sense or not.

[Google protobuf wrappers](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto#L69) which is a huge popular set of proto messages uses the detached leading line approach, for example: 
```proto
// Wrapper message for `int64`.
//
// The JSON representation for `Int64Value` is JSON string.
message Int64Value {
  // The int64 value.
  int64 value = 1;
}
```
so does other APIs like [kubernetes](https://github.com/kubernetes/api/blob/master/core/v1/generated.proto#L33) and [istio](https://github.com/istio/istio/blob/master/common-protos/google/rpc/code.proto#L25). Although this seems to be a very common approach coming from the Golang Style (where the comments start with the name of the entity being described, read [this](https://go.dev/doc/effective_go#commentary)) I feel like **it only happens when the description is long**, if the description is short (e.g. one line) there is not separation of title/description.

Others like [envoy uses protodoc](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/bootstrap/v2/bootstrap.proto#L31):
```
// [#protodoc-title: Bootstrap]
// This proto is supplied via the :option:`-c` CLI flag and acts as the root
// of the Envoy v2 configuration. See the :ref:`v2 configuration overview
// <config_overview_bootstrap>` for more detail.

// Bootstrap :ref:`configuration overview <config_overview_bootstrap>`.
// [#next-free-field: 21]
message Bootstrap {
```

I think supporting protodoc can be a separated discussion and I will open an issue for that as it is quite used (e.g. https://github.com/search?l=Protocol+Buffer&q=protodoc&type=code)

**Comment by yudintsevegor** [comment]
Hey folks, 
this is something useful for us. We are currently doing it manually, we will be happy to see it in the future :) 
Thanks a lot @mrozycki-tink  for the suggestion!

**Comment by jcchavezs** [comment]
I am giving a second thought on what I wrote yesterday. I think the reference use case:

```proto
// Thing
//
// This is a thing.
message Thing {
  ...
}
```

**Is very arbitrary.** None of the examples I posted (of widely used proto files) are following this pattern. Implementing the first detached line approach we would end up with titles like:

- [`Wrapper message for int64.`](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto#L69) for `Int64Value`
- [`Represents a Persistent Disk resource in AWS.`](https://github.com/kubernetes/api/blob/master/core/v1/generated.proto#L33) for `AWSElasticBlockStoreVolumeSource`
- [`Api is a light-weight descriptor for an API Interface.`](https://github.com/istio/istio/blob/master/common-protos/google/protobuf/api.proto#L45) for `Api`
- [`[#protodoc-title: Bootstrap]`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/bootstrap/v2/bootstrap.proto#L31) for Bootstrap
 
**Are they actual titles? I don't think so**, if any `[#protodoc-title: Bootstrap]` is an actual attempt to define a title. I think the easiest, more intuitive and less opinionated is to use the name of the main message (the one which isn't included in other message) and turn camel case (following proto naming convention) into spaces.

This will produce:

- [`In t64 Value`](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto#L72) for `Int64Value`
- [`AWS Elastic Block Store Volume Source`](https://github.com/kubernetes/api/blob/master/core/v1/generated.proto#L39) for `AWSElasticBlockStoreVolumeSource`
- [`Api`](https://github.com/istio/istio/blob/master/common-protos/google/protobuf/api.proto#L45) for `Api`
- [`Bootstrap`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/bootstrap/v2/bootstrap.proto#L38) for Bootstrap

Does that work for you all?

**Comment by chrusty** [comment]
So how about my idea of using the _detached_ comments? Support for this is built into the proto ecosystem, it just makes sense to me.

I'm disinclined to introduce support for something like `[#protodoc-title: Bootstrap]` at this stage if we can do what we want with a simple solution which is already supported by the libraries in use.

**Comment by jcchavezs** [comment]
> So how about my idea of using the detached comments? Support for this is built into the proto ecosystem, it just makes sense to me.

Do you have any link about this? I am curious.

@chrusty I think the idea of detached comments made sense to me at the beginning but I can't find a single proto out there that would produce a correct output (as pointed out before).

**Comment by chrusty** [comment]
@jcchavezs let me clarify:

Detached comment is two comments separated by an empty line:

```
// Detached comment

// Rest of comments
```

This is natively supported by the protobuf libraries, and doesn't cause any drama for existing behaviour.

**Comment by chrusty** [comment]
> > So how about my idea of using the detached comments? Support for this is built into the proto ecosystem, it just makes sense to me.
> 
> Do you have any link about this? I am curious.
> 
> @chrusty I think the idea of detached comments made sense to me at the beginning but I can't find a single proto out there that would produce a correct output (as pointed out before).
> 
> Agree `protodoc` isn't a way to go now as it is only supported by Envoy (no tool to render it outside envoy's world).

https://github.com/protocolbuffers/protobuf-go/blob/master/types/descriptorpb/descriptor.pb.go#L2817

**Comment by chrusty** [comment]
I'm not that worried about _existing_ protos generating a Title, more interested in allowing people to write their protos in such a way that they can get titles to generate if they want them to.

**Comment by jcchavezs** [comment]
I think after reading the documentation of the detached code and what I said before I am still inclined to say titles should come from the root message name instead of coming up with a new convention that will only be used in here. In my use case I want to generate a jsonschema out of existing proto (specifically envoy). I don't see they accepting I change the format of the comment in the proto to support a convention that only happens in this repo. Same way I don't see other projects doing it. I think the less intrusive, more intuitive and also not breaking changes required is that we do `MyCustomMessage -> My custom message`. What do you think about that proposal?

**Comment by chrusty** [comment]
OK how about this:
- Title becomes the detached leading comment if it exists
- Otherwise Title is derived from the message name (in the way you've described) if it doesn't exist

Sound reasonable?

**Comment by chrusty** [comment]
@jcchavezs and @mrozycki-tink, I've merged this PR into the master branch now. Would you guys be able to have a go and let me know if this works for you?

**Comment by jcchavezs** [comment]
Thanks I think the message name approach would fix the problem for both of
us. Not sure if the detached comment was still needed. In any case I will
give it a try today.

**Comment by yudintsevegor** [comment]
Hey! @chrusty 

I see that you merged the PR, thank you so much!

1) Are you going to update versions in releases?
2) I want to point out that there is an "unexpected" behavior for the `description` field:
proto:
```
// PackageStatusUpdated

// PackageStatusUpdated is published to the topic
message PackageStatusUpdated {
```

jsonschema:
```
"title": "PackageStatusUpdated",
 "description": "PackageStatusUpdated  PackageStatusUpdated is published to the topic"
```

it also takes detached comments to the description.

**Comment by chrusty** [comment]
> Hey! @chrusty
> 
> I see that you merged the PR, thank you so much!
> 
>     1. Are you going to update versions in releases?
> 
>     2. I want to point out that there is an "unexpected" behavior for the `description` field:
>        proto:
> 
> 
> ```
> // PackageStatusUpdated
> 
> // PackageStatusUpdated is published to the topic
> message PackageStatusUpdated {
> ```
> 
> jsonschema:
> 
> ```
> "title": "PackageStatusUpdated",
>  "description": "PackageStatusUpdated  PackageStatusUpdated is published to the topic"
> ```
> 
> it also takes detached comments to the description.

Hi @yudintsevegor, thanks for your interest. The behaviour you've pointed out isn't entirely "unexpected" to me... this is the existing default behaviour, and I'd like to avoid changing that. There may be people out there who are only interested in the "description" field and would expect to see _all_ comments in there.

**Comment by yudintsevegor** [comment]
Thank you so much! get it!

**Comment by chrusty** [comment]
I've made this change, merged it, and included in a new release: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.3.6

Thanks again for your interest in the project!
