### ISSUE TITLE
Remove new lines in descriptions.

### ISSUE THREAD

**Issue by jcchavezs** [chrusty/protoc-gen-jsonschema#109]
Generated JSON schema descriptions contain new lines chars which are meaningless in a description, caused mainly by the parsed I think. For example in https://github.com/envoyproxy/envoy/blob/9d5627a0879b0a029e90515137c108e1d2884bfc/api/envoy/config/accesslog/v3/accesslog.proto#L33-L35

```
  // The name of the access log extension to instantiate.
  // The name must match one of the compiled in loggers.
  // See the :ref:`extensions listed in typed_config below <extension_category_envoy.access_loggers>` for the default list of available loggers.
  string name = 1;
```

generates something like:

```
"properties": {
    "name": {
        "type": "string",
        "description": "The name of the access log extension to instantiate.\n The name must match one of the compiled in loggers.\n See the :ref:`extensions listed in typed_config below \u003cextension_category_envoy.access_loggers\u003e` for the default list of available loggers."
    },
```

If not default case I believe it deserves an option.

I am happy to work it out myself.

**Comment by chrusty** [comment]
Hi @jcchavezs, thanks for raising this. Would you suggest just stripping the '\n' from description fields?

**Comment by jcchavezs** [comment]
I think so. My main thought on this is that the single new lines are mainly
unintentional, following a max line size rule in proto files. More than one
new line is most likely to be user intent.

**Comment by chrusty** [comment]
Actually those newline characters are disgusting. They should totally be stripped.

**Comment by jcchavezs** [comment]
Do you want me to come up with a PR?

**Comment by chrusty** [comment]
No it's OK i can handle that

**Comment by chrusty** [comment]
Hi @jcchavezs, I just merged a fix for this: https://github.com/chrusty/protoc-gen-jsonschema/pull/113

I'll make a release soon

**Comment by chrusty** [comment]
I've made this change, merged it, and included in a new release: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.3.6

Thanks again for your interest in the project!
