### ISSUE TITLE
proto3: 'package' is optional

### ISSUE THREAD

**Issue by amarkevich** [chrusty/protoc-gen-jsonschema#111]
Actual: `level=warning msg="Proto file doesn't specify a package" filename=common.proto`
Expected: process files without [package](https://developers.google.com/protocol-buffers/docs/proto3#packages) specifier

**Comment by chrusty** [comment]
I've made this change, merged it, and included in a new release: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.3.6

Thanks again for your interest in the project!
