### ISSUE TITLE
go get is deprecated: update Readme to use go install

### ISSUE THREAD

**Issue by christiaanpauw** [chrusty/protoc-gen-jsonschema#115]
uninstalling with :
GO111MODULE=on \
go get github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema &&
go install github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema

as advised results in:

go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
go install: version is required when current directory is not in a module
	Try 'go install github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema@latest' to install the latest version

**Comment by chrusty** [comment]
Hi @christiaanpauw, thanks for raising this. About time it was updated!

I've pushed a commit which addresses this: https://github.com/chrusty/protoc-gen-jsonschema/commit/7587d72b5b0f5ae99a696e33e5ee31a32f5f875c - this will be included in the next released version.

Thanks for your interest in the project!
