### ISSUE TITLE
Bug when disallowing bigints and allowing null values.

### ISSUE THREAD

**Issue by dbedari-indeed** [chrusty/protoc-gen-jsonschema#119]
When using `disallow_bigints_as_strings` and `allow_null_values`, one ends up getting a schema as such:
```
                "someJsonField": {
                    "type": "integer",
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
```
While both work perfectly separately, combining them seems to give us a logical error.

**Comment by chrusty** [comment]
Hi @dbedari-indeed, thanks for raising this. I'll take a look over the next day or two and see what I can come up with.

My apologies for the delay in responding.

**Comment by dbedari-indeed** [comment]
No problem at all. I really appreciate you taking a look at this!

**Comment by chrusty** [comment]
Hi @dbedari-indeed. I've made a fix for this, and merged it into the `master` branch. Would you be able to give this a go, and tell me if it does what you want now?

Once you're happy with that I'll tag a new release.

**Comment by dbedari-indeed** [comment]
Thank you so much @chrusty; confirmed the fix works. Appreciate your patch, and thank you for the awesome tool!

**Comment by chrusty** [comment]
I've made a [new release](https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.3.8) which contains this fix now.

Thanks again.
