### ISSUE TITLE
How do I generate json schema for grpc service proto ?

### ISSUE THREAD

**Issue by yashdesai7** [chrusty/protoc-gen-jsonschema#125]
I would like to use this to generate json schema for service proto which looks like below 

```
service GetSomeThingService {
    rpc Get(stream ClientMessage) returns (stream ServiceMessage);
}

```

How do I do that ? 

I tried generating schema but It only generated schema for  `ClientMessage` and `ServiceMessage` but not for `GetSomeThingService`

**Comment by chrusty** [comment]
Hi @yashdesai7, interesting question here. I'm sorry to say that this project was only ever aiming to generate schemas for the payloads themselves. I'm not even sure that JSONSchema would make much sense of an RPC definition! Have a look at [this link here](https://stackoverflow.com/questions/54164062/json-rpc-schema-specification) - these guys are discussing this very issue.

I know this is not the answer you were looking for, sorry I can't be of more use here. The only thing which may be of use to you is OpenAPI / Swagger, which is specifically designed to define APIs with request and response payloads. For the most part it maps quite well to JSONSchema.
