### ISSUE TITLE
Compatibility with protobuf gradle plugin

### ISSUE THREAD

**Issue by Rustem** [chrusty/protoc-gen-jsonschema#133]
Hi there, thanks so much for your wonderful tool. 
I am wondering how to make it compatible with [gradle-protobuf-plugin](https://github.com/google/protobuf-gradle-plugin). Similarly to grpc, i d like to generate json schema files out of proto files during compilation of my project. 

Could you please suggest the path forward ?

**Comment by Rustem** [comment]
Unable to delete. I was able to make it working with protobuf plugin

**Comment by chrusty** [comment]
Hey @Rustem, sounds like you solved the problem then? That is good, because I don't know much about Gradle and the Java ecosystem.

I'm pleased you got it to work. Thanks for your interest in the project!

ps If this is something potentially tricky then perhaps you could post the solution here?
