### ISSUE TITLE
Move configuration parameters from jsonschema_out to jsonschema_opt

### ISSUE THREAD

**Issue by michaelrosett** [chrusty/protoc-gen-jsonschema#136]
In order to use bufbuild's [`buf generate`](https://docs.buf.build/configuration/v1/buf-gen-yaml) command, the `plugins.out` field cannot be of the form, for example, `enforce_oneof,file_extension=schema.json,disallow_additional_properties:schemas`. 

You README indicates you don't like this cli syntax and the good news is that protoc plugins should use the `_opt` suffix which would allow you to do something like the following instead. And this would work with bufbuild!
 
```
protoc \
  --plugin=${HOME}/go/bin/protoc-gen-jsonschema \
  --jsonschema_opt=enforce_oneof
  --jsonschema_opt=file_extension=schema.json \
  --jsonschema_opt=disallow_additional_properties \
  --jsonschema_out=schemas \
  --proto_path=proto
```

**Comment by michaelrosett** [comment]
In fact, this already works. Should probably recommend this syntax over comma separated jsonschema_out paramter.

**Comment by chrusty** [comment]
Glad it works for you. I'll update the docs. All of that option parsing is handled by the protobuf toolkit _before_ it gets to protoc-gen-jsonschema, so it should all be fairly standard stuff.
