### ISSUE TITLE
Using proto options breaks go proto gen

### ISSUE THREAD

**Issue by betamike** [chrusty/protoc-gen-jsonschema#137]
Hello! 

I have a use case where I want to generate a JSON schema from a proto also being used in existing Go code.

I've found that importing `options.proto` leads `protoc-gen-go` to generate an invalid import:
```
<...>
import (
        _ "./protos"
        protoreflect "google.golang.org/protobuf/reflect/protoreflect"
        protoimpl "google.golang.org/protobuf/runtime/protoimpl"
        reflect "reflect"
        sync "sync"
)
<...>
```

I'm not sure what the _right_ way to handle this is, but I can provide an example from what I've seen [protoc-gen-validate
](https://github.com/bufbuild/protoc-gen-validate) do: 

Its [options file ](https://github.com/bufbuild/protoc-gen-validate/blob/main/validate/validate.proto) uses a [`go_package`](https://github.com/bufbuild/protoc-gen-validate/blob/main/validate/validate.proto#L4) option that points to a public go module.

`github.com/bufbuild/protoc-gen-validate/blob/main/validate/validate.proto`:
```
syntax = "proto2";
package validate;

option go_package = "github.com/envoyproxy/protoc-gen-validate/validate";
option java_package = "io.envoyproxy.pgv.validate";
<...>
```

which results in a valid import in generated files:

```
<...>

import (
        _ "github.com/envoyproxy/protoc-gen-validate/validate"
        protoreflect "google.golang.org/protobuf/reflect/protoreflect"
        protoimpl "google.golang.org/protobuf/runtime/protoimpl"
<...>
```

**Comment by chrusty** [comment]
Hi @betamike , thanks for raising this.

It should be a relatively simple change. I'll have a look at it this evening and let you know when something is ready to test.

**Comment by chrusty** [comment]
OK @betamike I've pushed some changes to the master branch. Can you give that a go and let me know if it solves the issue for you?

**Comment by betamike** [comment]
Hey @chrusty! Just tested this out and it does solve my issue! Thank you!

**Comment by chrusty** [comment]
Alright, great to hear that. I've made a new release with this included: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.4.0

Thanks for your interest in the project, @betamike!
