### ISSUE TITLE
Struct and Value should always allow additional properties

### ISSUE THREAD

**Issue by tigersoldier** [chrusty/protoc-gen-jsonschema#141]
Currently if setting `disallow_additional_properties` in the protoc options, the schema for Struct or Value won't allow any properties in them. There is no way to override it via proto options since `disallow_additional_properties` is a message-wide option, not a field-wide option.

The workaround is not setting `disallow_additional_properties` globally and setting it on each proto message definitions by using the message-wide option. This is pretty annoying though.

**Comment by chrusty** [comment]
Hello @tigersoldier, sorry for taking so long with a response here.

Are you talking specifically about `google.protobuf.Struct` and `google.protobuf.Value` here?

**Comment by chrusty** [comment]
Hi @tigersoldier, I've made a [PR](https://github.com/chrusty/protoc-gen-jsonschema/pull/149) which addresses this issue.

I'll merge it in to master now. Please let me know if this doesn't solve the problem for you.
