### ISSUE TITLE
Wrong schema generated for google.protobuf.ListValue

### ISSUE THREAD

**Issue by oliver** [chrusty/protoc-gen-jsonschema#143]
When using the `google.protobuf.ListValue` type from [struct.proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto), Protobuf will actually use an array in JSON, but the generated JSON Schema does not reflect that.

E.g. for this .proto file:

```protobuf
syntax = "proto2";
import "google/protobuf/struct.proto";

message SomeTestMessage {
  required int32 some_int = 1;
  required google.protobuf.ListValue some_list = 2;
}
```

and this C++ code:
```c++
rbc::SomeTestMessage test_msg;
test_msg.set_some_int(42);
{
  google::protobuf::Value v;
  v.set_number_value(3.1415);
  test_msg.mutable_some_list()->mutable_values()->Add(std::move(v));
}
{
  google::protobuf::Value v;
  v.set_number_value(2.7182);
  test_msg.mutable_some_list()->mutable_values()->Add(std::move(v));
}
std::string json_string;
google::protobuf::util::MessageToJsonString(test_msg, &json_string);
std::cout << "json_string: " << json_string << std::endl;
```

the following JSON will be written:

```json
{
  "some_int": 42,
  "some_list": [3.1415, 2.7182]
}
```

But the JSON Schema generated by protoc-gen-jsonschema describes that `some_list` is an object with a `values` member. When validating the created JSON string against the generated Schema file, validation fails.

I guess this happens because Protobuf has special code for serializing these well-known types to/from JSON.

**Comment by chrusty** [comment]
Hello @oliver, thanks for raising this.

We aready have some specific cases for generating Google protobuf types. This probably be added without too much hassle. I'll take a look.

**Comment by chrusty** [comment]
Hi @oliver, I've made a PR for this: https://github.com/chrusty/protoc-gen-jsonschema/pull/145

Would you be able to try that branch out and tell me if this does what you're after?

**Comment by oliver** [comment]
Yes, I'll give it a try tomorrow. Thanks for the quick PR!

**Comment by chrusty** [comment]
Hey @oliver, I've made a new release containing the update: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.4.1

**Comment by oliver** [comment]
Great, much appreciated! Thank you for this project, it's really useful for me!
