### ISSUE TITLE
No way to generate minItems=x on arrays

### ISSUE THREAD

**Issue by benoit-campeau** [chrusty/protoc-gen-jsonschema#144]
In Json Schema we can add minItems=1 on a array definition to make it non-empty.

example
`        "localizations": {
          "minItems": 1,
          "items": {
            "$ref": "#/Localization"
          },
          "type": "array",
          "description": "localized values for this title scope and type."
        }
`

I don't see a way to do that... did i miss something

**Comment by chrusty** [comment]
Hi @benoit-campeau. This should be possible... the main issue would be agreeing on a standard for expressing these validation rules in the proto files themselves.

The [protoc-gen-validate](https://github.com/bufbuild/protoc-gen-validate) project offers something here. With a bit of work we could support those options and get the validation rules into our generated JSON Schemas.

**Comment by chrusty** [comment]
Hello @benoit-campeau, I've added some initial support for these validation rules. I've got a [PR](https://github.com/chrusty/protoc-gen-jsonschema/pull/146) here.

Have a look at [this file](internal/converter/testdata/proto/ValidationOptions.proto) for an example of how to add these rules to your protos.

**Comment by chrusty** [comment]
I've merged this into the master branch. Please have a go using this. If this works for you then I can tag a release.

Thank you for your interest in the project!
