### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by whuang8** [chrusty/protoc-gen-jsonschema#15]
Hi @chrusty,

With the new changes in https://github.com/chrusty/protoc-gen-jsonschema/pull/14, I am confused about the new way of installing `protoc-gen-jsonschema`.

Before the change, running `go get git.enova.com/cashnet/protoc-gen-go` worked well since `main.go` was still in the top level directory. Now, there doesn't seem to exist a `main.go` or any main package at all that can be built.

Running `make build` or `go install github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema` as instructed by the README leads to errors regarding `github.com/chrusty/protoc-gen-jsonschema/cmd` not existing. Is there something I am missing here?

I appreciate your help!

**Comment by chrusty** [comment]
Hi @whuang8, sorry about that. I only just merged that in today and it looks like I'd omitted the entire `/cmd` directory.

- I've updated the `Makefile` (so you should be able to do `make install` from the project root)
- I've also updated the README with (what should hopefully be) the correct installation instructions

Please let me know if you still have trouble with it.
