### ISSUE TITLE
bug: enforce_oneof with json_fieldnames results in inconsistent schema

### ISSUE THREAD

**Issue by sherif-elmetainy** [chrusty/protoc-gen-jsonschema#152]
Hello and thanks for this nice package.

I encountered the following problem with generating schemas using the following options:
```bash
protoc --plugin=$HOME/go/bin/protoc-gen-jsonschema --jsonschema_opt=enforce_oneof --jsonschema_opt=file_extension=schema.json --jsonschema_out=json_fieldnames:. --proto_path=. my_message.proto

```
I use snake_case for the field names. for example `my_first_field`. the `enforce_oneof` option results in `oneOf` property in the schema having the field names in snake_case. However, the `json_fieldname` option causes the `properties` property in the schema to list the fields using camelCase.  This inconsistency result in schema that can never be valid.

Here is a test message to demonstrate the problem:

```proto
message MyMessage {
    optional string my_first_field = 1;
    optional string my_second_field = 2;
}
```

And here is the schema generated by running the command:
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "#/definitions/MyMessage",
    "definitions": {
        "MyMessage": {
            "properties": {
                "myFirstField": {
                    "type": "string"
                },
                "mySecondField": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "type": "object",
            "oneOf": [
                {
                    "required": [
                        "my_first_field"
                    ]
                },
                {
                    "required": [
                        "my_second_field"
                    ]
                }
            ],
            "title": "My Message"
        }
    }
}
```

**Comment by chrusty** [comment]
Hello @sherif-elmetainy. I've merged a PR which may affect your issue. Are you able to build the latest master branch and give it a try?

**Comment by sherif-elmetainy** [comment]
@chrusty 
Thanks for the fix. The latest version fixed the bug. Now the oneOf properties and the properties are both using camel case.
