### ISSUE TITLE
Help wanted - Syntax for Array of object is not following specification

### ISSUE THREAD

**Issue by MaxTibs** [chrusty/protoc-gen-jsonschema#154]
Hi,

I'm trying to generate code out of the generated schema, but it seems that the generator I'm using is having hard time understanding the syntax for Array of object generated by this project. This behavior happens when using `allow_null_values` 

So, I'm wondering if there is an issue with this project. 

## How to reproduce

Given I have 
https://github.com/chrusty/protoc-gen-jsonschema/blob/master/internal/converter/testdata/proto/ArrayOfObjects.proto
```
syntax = "proto3";
package samples;

message ArrayOfObjects {
    message RepeatedPayload {
        enum Topology {
            FLAT             = 0;
            NESTED_OBJECT    = 1;
            NESTED_MESSAGE   = 2;
            ARRAY_OF_TYPE    = 3;
            ARRAY_OF_OBJECT  = 4;
            ARRAY_OF_MESSAGE = 5;
        }

        string name       = 1;
        string timestamp  = 2;
        int32 id          = 3;
        float rating      = 4;
        bool complete     = 5;
        Topology topology = 6;
    }

    string description               = 1;
    repeated RepeatedPayload payload = 2;
}
```

The observed output for payload is
https://github.com/chrusty/protoc-gen-jsonschema/blob/master/jsonschemas/ArrayOfObjects.json
```
"payload": {
    "items": {
        "$ref": "#/definitions/samples.ArrayOfObjects.RepeatedPayload"
    },
    "oneOf": [
        {
            "type": "null"
        },
        {
            "type": "array"
        }
    ]
}
```

I've look at the [draft-4 specifications](https://datatracker.ietf.org/doc/html/draft-zyp-json-schema-04) and it looks like that the "items" property has to be at the same level as the "type". 

So the expected output would instead be:
```
"payload": {
    "oneOf": [
        {
            "type": "null"
        },
        {
            "type": "array",
            "items": {
                "$ref": "#/definitions/samples.ArrayOfObjects.RepeatedPayload"
            },
        }
    ]
}
```

I could be wrong, but in case this is a valid syntax following the specification, do you know a way I could remap the fields correctly? 

Thanks for your help!

**Comment by chrusty** [comment]
Thanks @MaxTibs, this looks legit. I've merged it in so you can run it from latest master until I've made a new release.
