### ISSUE TITLE
Support for 'description' options

### ISSUE THREAD

**Issue by Mishkun** [chrusty/protoc-gen-jsonschema#155]
Hi! Thanks for the awesome package. One crucial thing for documenting a schema is missing though – "description". This can be supported by custom field option like this:

```proto
message IssueNotification {
 string resolution = 6 [(protoc.gen.jsonschema.field_options).description = "Resolution ID"];
}
```

**Comment by chrusty** [comment]
Hi @Mishkun, thanks for your interest!

We actually already support descriptions in a different way. Take a look at this example:

- [Proto with comments](https://github.com/chrusty/protoc-gen-jsonschema/blob/master/internal/converter/testdata/proto/MessageWithComments.proto)
- [JSONSchema it becomes](https://github.com/chrusty/protoc-gen-jsonschema/blob/master/internal/converter/testdata/message_with_comments.go)

Yeah we _could_ do it with an option too, but hopefully this existing way works for you.

**Comment by Mishkun** [comment]
Oh, wow! Did not see that in the readme. It will work for me, thanks!
