### ISSUE TITLE
Generating json schema for nested message

### ISSUE THREAD

**Issue by pativa** [chrusty/protoc-gen-jsonschema#166]
Hi,

Thank you for this project. I've been using it to generate json schema and then from this generating a form for testing rpc services.

I'm wondering if there is any way to generate the schema for a proto that looks like this:

```proto
syntax = "proto3";

service ExampleService {
        rpc ExampleRpc (Namespace.ExampleRequest) returns (Namespace.ExampleResponse) {}
}

message Namespace {
        message ExampleRequest {
                string payload = 1;
        }

        message ExampleResponse {
                string payload = 1;
        }
}
```

My issue is that I can only get the following schema from this file:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "#/definitions/Namespace",
    "definitions": {
        "Namespace": {
            "additionalProperties": true,
            "type": "object",
            "title": "Namespace"
        }
    }
}
```

Ideally, I would like to be able to run the command like this:

```sh
protoc --plugin=${HOME}/go/bin/protoc-gen-jsonschema --jsonschema_out="messages=[Namespace.ExampleRequest]:." example.proto
```
in order to generate the schema for `Context.ExampleRequest`, but this does not work.

Is there any way to generate the schema for a proto file formatted like this? Changing the original protofile is unfortunately not an option for me.

**Comment by chrusty** [comment]
Hello @pativa.

I'm fairly sure this would work if you included a package name, and made use of the nested schemas. At the moment your "Namespace" message just _defines_ two nested messages, but doesn't make use of them. This converter will only create schemas for messages that are actually used. This example works:

```proto
syntax = "proto3";
package example;

service ExampleService {
        rpc ExampleRpc (Namespace.ExampleRequest) returns (Namespace.ExampleResponse) {}
}

message Namespace {
        message ExampleRequest {
                string payload = 1;
        }

        message ExampleResponse {
                string payload = 1;
        }

        ExampleRequest request = 1;
        ExampleResponse response = 2;
        string something_else = 3;
}
```
