### ISSUE TITLE
Add support for numerics

### ISSUE THREAD

**Issue by mxplusb** [chrusty/protoc-gen-jsonschema#171]
I have several protobuf fields that use `uint64`. When I use the schema generator, it creates those fields as `string`. It would be very helpful if it could generate those fields as `number`.

**Comment by ezzothedj** [comment]
Hey @mxplusb, I had this same issue when generating ```uint64``` type fields. You can use the ```disallow_bigints_as_strings``` configuration parameter flag in your command to generate them as an ```integer``` type.

Hope this helps you out!
