### ISSUE TITLE
including comments in the file

### ISSUE THREAD

**Issue by grossd** [chrusty/protoc-gen-jsonschema#176]
Hello, 

Nico from https://buf.build/ was so kind to mention protoc to jsonschema project. 

Its what I was looking for, but it seems that it misses one descriptor capability -- to access comments in protobuf files. 

Would be great if json could also include comments in the file -- i think there are also ways to indicate where a comment is placed. 

thanks,

Dan

**Comment by chrusty** [comment]
Hi @grossd. Proto file comments are already being used in several places here to infer various things.

Take a look at [this example](https://github.com/chrusty/protoc-gen-jsonschema/blob/master/internal/converter/testdata/proto/MessageWithComments.proto), and [what it turns into](https://github.com/chrusty/protoc-gen-jsonschema/blob/master/internal/converter/testdata/message_with_comments.go).
