### ISSUE TITLE
With NestedMessage, syntaxe for  $ref (URI-reference) should start with # 

### ISSUE THREAD

**Issue by Hugues514** [chrusty/protoc-gen-jsonschema#24]
Your tool is great, very helpfull.
When I take the Enumception.jsonschema it seems that the syntaxe for the reuse of structure PayloadMessage seems incorrect (at least in the faker tool that I used...) the line is : 
            "$ref": "samples.PayloadMessage",
and should be 
            "$ref": "#/samples.PayloadMessage",

Otherwise the reference to the definition located in the same file is not found.
Here is the doc explaining this : 
https://json-schema.org/understanding-json-schema/structuring.html

**Comment by chrusty** [comment]
Hi @Hugues514, thanks for your interest!

I spent some time looking into this today. On first glance you are correct - this isn't the correct format for a reference. However, the document you linked [_does_ mention](https://json-schema.org/understanding-json-schema/structuring.html#the-id-property) `ID`, which is how these schemas are generated..

I tested the generated enumception schema using https://www.jsonschemavalidator.net/, which _does_ understand what is being done here.

Does this answer your question? I find that the main problem when dealing with JSONSchemas is finding the right library to perform the validations. Hopefully you can find one in your language that supports this.
