### ISSUE TITLE
Generator fails if proto has no package

### ISSUE THREAD

**Issue by xylo04** [chrusty/protoc-gen-jsonschema#26]
I was attempting to generate a JSON schema for a new proto file. Even debug output only hinted at the problem:

```
$ protoc --jsonschema_out=debug:./jsonschema/ test.proto 
DEBU[0000] Converting input                             
DEBU[0000] Loading a message                             msg_name=Timestamp package_name=google.protobuf
DEBU[0000] Loading a message                             msg_name=TestMessage package_name=
DEBU[0000] Converting file                               filename=test.proto
DEBU[0000] Serializing code generator response          
WARN[0000] Failed to process code generator but successfully sent the error to protoc 
--jsonschema_out: protoc-gen-jsonschema: Plugin failed with status code 1.
```

Once I add a `package` to my proto, the generator works. I probably should have done this with my proto anyway, but since `package` is optional, the generator shouldn't die, or should at least have a more clear error message.

**Comment by chrusty** [comment]
Good catch. I'll At least add an error message and test for the missing package name. Sorry if this caused you any trouble.

**Comment by xylo04** [comment]
No worries! Thanks for putting this together

**Comment by chrusty** [comment]
Alright, I've included a warning message now.
