### ISSUE TITLE
Is there any parameter to generate a jsonschema file using package name as file name prefix?

### ISSUE THREAD

**Issue by YuanYingdong** [chrusty/protoc-gen-jsonschema#27]

**Comment by chrusty** [comment]
Hi @YuanYingdong, no there is no option for this at the moment. Generally I'd run it against a directory of proto files in one package, and write schemas out to a specific folder for them.

Having said that, it would be easy enough to add this. I could get it to create a directory for each package, OR prefix the filename. I'm wondering what would be more useful to more people.

**Comment by YuanYingdong** [comment]
Got it, thank you!
