### ISSUE TITLE
It seems that this tool can't handle the required keyword in protobuffer2

### ISSUE THREAD

**Issue by YuanYingdong** [chrusty/protoc-gen-jsonschema#30]
It seems that this tool can't handle the required keyword in protobuffer2, but this can be handled by the Protobuffer's Json convert utils.
Is there any parameter to set all fields in pb3 Message to be required in the JSON schema?

**Comment by YuanYingdong** [comment]
When checking a '{}' Json string, the Jsonschema generated from protobuffer 3 message will always result in a successful checking.

**Comment by chrusty** [comment]
I've got an old branch which deals with this, i'll bring it back now. I guess the "required fields" features kinda became redundant with proto3, but I'm happy to add this for proto2 users.

**Comment by chrusty** [comment]
@YuanYingdong how does this look? https://github.com/chrusty/protoc-gen-jsonschema/pull/33

**Comment by chrusty** [comment]
@YuanYingdong I've made a new release: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/0.9.2

Please let me know how you get on with it!

**Comment by YuanYingdong** [comment]
Ok, I'll try it later
