### ISSUE TITLE
Allow Only JSON Field Names

### ISSUE THREAD

**Issue by grant** [chrusty/protoc-gen-jsonschema#38]
There is no option to _only_ allow JSON Field names, only an option to allow proto field names or proto AND json field names

## Proposal

- Current config: `proto_and_json_fieldnames` (includes both proto and json field names)
- Requested config: `json_fieldnames` (excludes proto field names)

## Relevant IF

https://github.com/chrusty/protoc-gen-jsonschema/blob/403865327248cbe778def570bcd2f8d16a92ac04/internal/converter/types.go#L477-L480

## Rough code

```go
		if !c.UseJSONFieldnamesOnly {
			jsonSchemaType.Properties.Set(fieldDesc.GetName(), recursedJSONSchemaType)
		} else if c.UseJSONFieldnamesOnly || (c.UseProtoAndJSONFieldnames && fieldDesc.GetName() != fieldDesc.GetJsonName()) {
			jsonSchemaType.Properties.Set(fieldDesc.GetJsonName(), recursedJSONSchemaType)
		}
```

**Comment by chrusty** [comment]
Hello again @grant! OK I can see the purpose of this request, and if you're happy for it to be hidden behind another config flag then i'm happy enough to add it in.

Sorry about the delayed response, but I have 4 clients at the moment so my keyboard is a bit busy.

**Comment by grant** [comment]
Yeah, just another config `json_fieldnames` would be cool.
We currently filter out the proto fieldnames in our client in a post-generation step; a native option would be good :)

**Comment by chrusty** [comment]
Hey @grant how does this PR look?

**Comment by chrusty** [comment]
New release with this feature: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/0.9.5
