### ISSUE TITLE
Int64 JSON Mapping Should Be String, Not OneOf

### ISSUE THREAD

**Issue by grant** [chrusty/protoc-gen-jsonschema#47]
All `int64` types (and variants) should be mapped to the `string` type, not a `oneOf: [ {type: 'string'},{type: 'integer'}]`.

This should be done because the JSON mapping for int64 is type `string`.

### References

JSON Mapping:

https://developers.google.com/protocol-buffers/docs/proto3#json

Code:

https://github.com/chrusty/protoc-gen-jsonschema/blob/7726bafee96859cdee2947f818544b2af809be75/internal/converter/types.go#L107

### Solutions

- String
  - The Proto spec states the mapping should be a `string`.
- String with Regex
  - Given the type is a `string`, we're optionally free to apply a regex to more strictly bind the string value to a regex. 
  - https://json-schema.org/understanding-json-schema/reference/string.html

### Related Issues

Mapping to a `oneOf` is causing a related issue for a jsonschema 2 golang file (using Quicktype): https://github.com/googleapis/google-cloudevents-go/issues/22#issuecomment-735578771

**Comment by chrusty** [comment]
Hey @grant, this seems like a valid issue. Hopefully it'll wrap up the other open issue too. Happy to implement this, fairly straight forward.

**Comment by grant** [comment]
No rush. This is a tricky issue. If you implement this, great!

**Comment by chrusty** [comment]
Hi @grant, had a chance to look at this. Have a look at the PR: https://github.com/chrusty/protoc-gen-jsonschema/pull/48

**Comment by grant** [comment]
👍

**Comment by chrusty** [comment]
OK that PR is merged. Let me know if it works for you and I'll make a new release.

**Comment by grant** [comment]
> OK that PR is merged. Let me know if it works for you and I'll make a new release.

This PR works for me.

**Comment by chrusty** [comment]
Releasted today: check https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/0.9.7
