### ISSUE TITLE
proto3 "bytes" field -> "contentEncoding=base64 string", not just "string"

### ISSUE THREAD

**Issue by grant** [chrusty/protoc-gen-jsonschema#50]
It would be nice if a proto3 `bytes` field stated in the JSON schema that the string is base64 encoded.

## Reference

- https://developers.google.com/protocol-buffers/docs/proto3
  - proto3 `bytes` field type => base64 string
- https://json-schema.org/understanding-json-schema/reference/non_json_data.html#id2
  - `"type": "string"`
  - (NEW) `"contentEncoding": "base64"` 

## Expected

- Add `"contentEncoding": "base64"` to byte fields.

Split up the proto type cases to something like this:

```go
	case descriptor.FieldDescriptorProto_TYPE_STRING:
		if c.AllowNullValues {
			jsonSchemaType.OneOf = []*jsonschema.Type{
				{Type: gojsonschema.TYPE_NULL},
				{Type: gojsonschema.TYPE_STRING},
			}
		} else {
			jsonSchemaType.Type = gojsonschema.TYPE_STRING
		}

	case descriptor.FieldDescriptorProto_TYPE_BYTES:
		if c.AllowNullValues {
			jsonSchemaType.OneOf = []*jsonschema.Type{
				{Type: gojsonschema.TYPE_NULL},
				{Type: gojsonschema.TYPE_STRING},
			}
		} else {
			jsonSchemaType.Type = gojsonschema.TYPE_STRING
			jsonSchemaType.Format = "binary"
		}
```

https://github.com/chrusty/protoc-gen-jsonschema/blob/master/internal/converter/types.go#L125-L134

**Comment by chrusty** [comment]
Hey @grant, this sounds reasonable enough. I'll get something in over the next few days (been away from computers for a couple of weeks).

**Comment by grant** [comment]
No rush!

**Comment by chrusty** [comment]
Hey @grant, I've merged the PR. Give it a try, let me know if it works for you, then I'll tag a release.

**Comment by grant** [comment]
Thanks! I've verified this generates better schemas.

**Comment by chrusty** [comment]
https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/0.9.8
