### ISSUE TITLE
No such package nor message in package

### ISSUE THREAD

**Issue by phlax** [chrusty/protoc-gen-jsonschema#52]
Im trying to understand the purpose of this message.

afaict this is triggered on conversion of every proto file where a package is specified (not specifying the package results in a warning) - and also on any "parent" packages if the package has `more.than.one.part`

i guess this can be safely ignored, but it creates a lot of noise when generating schemas from a large protocol set, and makes it diffficult to track any actual problems

**Comment by chrusty** [comment]
Hey @phlax, thanks for raising this. What you are saying makes sense - I can pretty easily change the severity of that log messing so it falls beneath the default threshold.

**Comment by chrusty** [comment]
@phlax are you able to give this another try, from the laster `master`? If that works for you I will tag a new release with these changes.

**Comment by phlax** [comment]
great! thanks
