### ISSUE TITLE
*structpb.Value type fields are not correctly interpreted to JSON Schema

### ISSUE THREAD

**Issue by geekpex** [chrusty/protoc-gen-jsonschema#55]
### Problem
With newer protobuf packages the struct fields that are of type *structpb.Value are outputted to JSON schema only as object and it does not allow other types that *structpb.Value supports (null, a number, a string, a boolean, a recursive struct value, or a list of values). This results in validation errors when the field value in JSON is for example string.

**Protobuf package versions:**

- google.golang.org/protobuf v1.25.0
- github.com/golang/protobuf v1.4.3

In these newer versions there is custom UnmarshalJSON/MarshalJSON methods for reading/writing the value correctly.

### Fix suggestion
The *structpb.Value fields should be written with "oneOf" field containing all supported types by structpb.Value.

Resulting field:

> "value": {
>                   "oneOf": [
>                       {
>                           "type": "number"
>                       },
>                       {
>                           "type": "string"
>                       },
>                       {
>                           "type": "boolean"
>                       },
>                       {
>                           "type": "object"
>                       },
>                       {
>                           "type": "array"
>                       }
>                   ]
>               },

(sorry about the formatting of json)

'null' is not included because that can be controlled with allow nulls flag.

Suggested fix to internal/converter/types.go:430

> 		case "Value":
> 			t := &jsonschema.Type{
> 				OneOf: []*jsonschema.Type{
> 					{Type: gojsonschema.TYPE_NUMBER},
> 					{Type: gojsonschema.TYPE_STRING},
> 					{Type: gojsonschema.TYPE_BOOLEAN},
> 					{Type: gojsonschema.TYPE_OBJECT},
> 					{Type: gojsonschema.TYPE_ARRAY},
> 				},
> 			}
> 
> 			if c.AllowNullValues {
> 				t.OneOf = append(t.OneOf, &jsonschema.Type{
> 					Type: gojsonschema.TYPE_NULL,
> 				})
> 			}
> 
> 			return t, nil
> 		}

**Comment by chrusty** [comment]
Thanks @geekpex , I'll take a look

**Comment by chrusty** [comment]
Hey @geekpex, I've [merged a PR into master](https://github.com/chrusty/protoc-gen-jsonschema/pull/57) which should address this.

Would you be able to give it a try, let me know if it has solved the issue?
