### ISSUE TITLE
google.protobuf.Any converted into value/binaryEncoding: base64

### ISSUE THREAD

**Issue by MP-85** [chrusty/protoc-gen-jsonschema#62]
Hello,
I am doing some tests with this nice library, but for what I have seen so far, google.protobuf.Any is associated to a base64 field in the json schema. I now that this is what happens when you try to serialize to json a protobuf including any, using classical json.Marshal(X). But, doing in this way you don't have anymore a readable file.
Instead, there is another way to serialize, using jsonpb.Unmarshal, that is able to serialize keeping all in clear.

It would be useful to have a similar feature here, that is not forcing google.protobuf.Any elements to be associated to a base64, maybe with a flag to describe how we want to handle similar situations. I don't think to have seen anything similar.

Could you have a look?

Thanks,
Marco

**Comment by chrusty** [comment]
Just looking at this now (sorry). It looks like a google.protobug.Any value currently maps to a base64 value, which I think is probably the only safe way to handle it (given that this could literally be anything). This approach _does_ seem a bit laborious, but at least can handle any situation.

https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/any

What would you prefer it to do in this situation? Remember when protoc-gen-jsonschema is producing schemas it doesn't know what you might be putting into these values.  Perhaps an option would be to include a flag which just sets google.protobuf.Any as type `OBJECT` with no further schema? You'd not get any validation then.

Sorry this took a while for me to pick up. Let me know what your thoughts are.
