### ISSUE TITLE
GoogleValue type descriptions aren't added to JSON Schema

### ISSUE THREAD

**Issue by grant** [chrusty/protoc-gen-jsonschema#65]
(Creating this issue for tracking purposes)

The descriptions for well known types are not added to the JSON schema. Example:

```proto
message GoogleValue {
  // My desc.
  google.protobuf.Value arg = 1;
}
```

We should expect `arg` to be a property and have a `description`.

```json
"properties": {
    "arg": {
        "description": "My desc."
        ...
    }
}
```

I think there is maybe something missing with:

```go
func formatDescription(sl *descriptor.SourceCodeInfo_Location) string {
```

https://github.com/chrusty/protoc-gen-jsonschema/blob/1.0.0/internal/converter/types.go#L527-L541

**Comment by chrusty** [comment]
I've merged a fix for this and made a pre-release: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/untagged-f8dda646aa02d3927db9

Let me know once you've been able to test it and I'll publish the release.
