### ISSUE TITLE
Add "format" property to google.protobuf.Duration string

### ISSUE THREAD

**Issue by grant** [chrusty/protoc-gen-jsonschema#66]
`google.protobuf.Duration` types should has a `format` / `pattern` property with the expected formats that are valid for this string.

Ref:
- https://github.com/chrusty/protoc-gen-jsonschema/issues/63
- https://json-schema.org/understanding-json-schema/reference/string.html

Examples:
- "3.000001s"
- "3s"

**Comment by chrusty** [comment]
A PR is open for this: https://github.com/chrusty/protoc-gen-jsonschema/pull/67

**Comment by chrusty** [comment]
I've merged a fix for this, and made a pre-release here: https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/untagged-f8dda646aa02d3927db9
