### ISSUE TITLE
Transient fields

### ISSUE THREAD

**Issue by marchesM** [chrusty/protoc-gen-jsonschema#69]
Idea would be to have an proto option to mark a field to not be added to the json schema, example:

```
message User {

  optional string name = 0;
  optional string email = 1;

  optional string type = 3 [(schemaTransient) = ""];
  repeated Address addresses = 4 [(schemaTransient) = ""];

}
```

which would output a json schema with only fields numbers 0 and 1, fields number 3 and 4 are not present in the json schema.

Goal of this:
use a message for the back end and allow to use the same message for the front end while being able to hide some fields because they are technical or soft managed and there's no point to pollute the schema with those

**Comment by chrusty** [comment]
Thanks for your idea @marchesM. At first glance this seems like something that could quite safely be introduced. Are you aware of any de-facto standard proto option we could use here?

**Comment by chrusty** [comment]
I'm wondering if we could use the `deprecated` field-option: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L613

I'd have to add an optional flag for `exclude_deprecated_fields` to avoid causing issues for anyone already using this field-option. Does this sound like a workable solution?

**Comment by chrusty** [comment]
OK I've got a PR which shows what this could look like: https://github.com/chrusty/protoc-gen-jsonschema/pull/71

It's a bit ugly, and I couldn't easily find a good way to iterate through these field options, but it _does_ work. I still need to add the feature flag to enable this behaviour because I don't really want it to be enabled by default.

**Comment by chrusty** [comment]
I've merged this into the `master` branch. Give it a go, and if it works for you then I'll make a new release.

**Comment by chrusty** [comment]
Alright well I've made a new release with this feature:

https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.0.3

Let me know if you get a chance to confirm that this works for you.

**Comment by chrusty** [comment]
I would like to point out that I have done this in quite a messy way, and have some [work in the pipeline](https://github.com/chrusty/protoc-gen-jsonschema/issues/79) to tidy up how these custom options are presented and interpreted. I've also [applied for an official options number in the protobuf repo](https://github.com/protocolbuffers/protobuf/pull/8999).

It means that in a future release you will have to use the protoc-gen-jsonschema options.proto in a slightly different way, but it shouldn't be a huge change for you. Just a heads up.

**Comment by chrusty** [comment]
OK, the new behaviour is live in https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.1.0

**Comment by marchesM** [comment]
Hi,
Thanks a lot even though I wasn't answering.
It's been a busy period. I'll definitely check this out in the next weeks.
