### ISSUE TITLE
I want to enforce_oneof and make all other properties except the ones in one of as required.

### ISSUE THREAD

**Issue by NoobMaster-96** [chrusty/protoc-gen-jsonschema#72]
I am trying to use enforce_oneof and all_fields_required at the same time. But this marks the individual one_of fields as required and thus enforce_oneof doesn't works, Is there any way to only make non one_of fields required.

**Comment by chrusty** [comment]
hey @NoobMaster-96, thanks for raising this. I'll take a look and see what can be done.

**Comment by chrusty** [comment]
@NoobMaster-96 please give the new release a try, and let me know if you're still having trouble with it.

https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.0.4

**Comment by NoobMaster-96** [comment]
hey @chrusty it's still not working as it's supposed to.
[jsonschemas/OneOf.jsonschema](https://github.com/chrusty/protoc-gen-jsonschema/blob/master/jsonschemas/OneOf.jsonschema) in this file you have done one of and all required but it's not making the field something as required.

**Comment by NoobMaster-96** [comment]
@chrusty I have a proto file.
`syntax = "proto3";

import "school/school.proto";
import "school/hs.proto";

package board;

message Board{
  string name = 1;
  repeated Schooltype listofschools = 2;

  message Schooltype{
    oneof School{
      school.School school = 1;
      school.HighSchool hschool = 2;
    }
  }
}
`

When I create a jsonschema with one of and all fields required it gives something like this

`{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "required": [
        "name",
        "listofschools"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "listofschools": {
            "items": {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "required": [
                    "school",
                    "hschool"
                ],
                "properties": {
                    "school": {
                        "required": [
                            "name",
                            "classes"
                        ],
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "classes": {
                                "items": {
                                    "$schema": "http://json-schema.org/draft-04/schema#",
                                    "$ref": "class.Class"
                                },
                                "additionalProperties": false,
                                "type": "array"
                            }
                        },
                        "additionalProperties": false,
                        "type": "object"
                    },
                    "hschool": {
                        "required": [
                            "name",
                            "classes",
                            "subjects"
                        ],
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "classes": {
                                "items": {
                                    "$schema": "http://json-schema.org/draft-04/schema#",
                                    "$ref": "class.Class"
                                },
                                "additionalProperties": false,
                                "type": "array"
                            },
                            "subjects": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false,
                        "type": "object"
                    }
                },
                "additionalProperties": false,
                "type": "object",
                "oneOf": [
                    {
                        "required": [
                            "school"
                        ]
                    },
                    {
                        "required": [
                            "hschool"
                        ]
                    }
                ]
            },
            "additionalProperties": false,
            "type": "array"
        }
    },
    "additionalProperties": false,
    "type": "object",
    "definitions": {
        "class.Class": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "properties": {
                "std": {
                    "type": "string"
                },
                "students": {
                    "items": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "required": [
                            "name",
                            "rollno"
                        ],
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "rollno": {
                                "type": "integer"
                            }
                        },
                        "additionalProperties": false,
                        "type": "object"
                    },
                    "additionalProperties": false,
                    "type": "array"
                }
            },
            "additionalProperties": false,
            "type": "object",
            "id": "class.Class"
        }
    }
}`

when you look inside of "listofschools" you can see it has marked both "school" and "hschool" as required and also created a one of between these fields at the end.

**Comment by chrusty** [comment]
Hey Avinash.

Which command are you using to generate? Try this one:

protoc --jsonschema_out=all_fields_required,enforce_oneof:. --proto_path=.
internal/converter/testdata/proto/OneOf.proto

**Comment by chrusty** [comment]
Also, are you able to provide all of your proto files? Then I can have a go at generating them myself and hopefully see where the problem is.

**Comment by NoobMaster-96** [comment]
You can find the proto files in this repo.
[proto folder](https://github.com/NoobMaster-96/Sample-protos

**Comment by NoobMaster-96** [comment]
I would also like to point to one more issue.
when it creates a reference like "class.Class" in the above provided schema. It doesn't make the fields of that reference required. As you can see inside the definition of "class.Class" the fields "std" and "students" are not marked as required.

**Comment by chrusty** [comment]
Alright, I've reopened this and will take a look.

**Comment by chrusty** [comment]
Hey @NoobMaster-96, I've just made a new branch https://github.com/chrusty/protoc-gen-jsonschema/tree/further_oneof_required_investigation

Would you be able to give this a try and see if it fixes your first issue? I'll look at the second one now.

**Comment by chrusty** [comment]
OK, the second issue might be good now as well (at least your protos seem to compile properly).

Please let me know if this works, and I'll merge then make a new release for you.

**Comment by NoobMaster-96** [comment]
Hey @chrusty both the issues are resolved with this branch. Thanks for the help.

**Comment by chrusty** [comment]
Awesome! Glad it is working now.

https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.0.6
