### ISSUE TITLE
$ref: broken?

### ISSUE THREAD

**Issue by neopaf** [chrusty/protoc-gen-jsonschema#73]
(thanks a lot for a superb plugin!)

Source:
[model.proto.txt](https://github.com/chrusty/protoc-gen-jsonschema/files/7186285/model.proto.txt)
e

I'm a bit confused about $ref codegeneration.
It get's generated "just.name.with.package.of.referred.entity".
This is not valid JSON reference, as I understand it.

Example of "wrong" `$ref` from `Party.jsonschema`:
```json
                "$ref": "ru.beeline.tmf.model.Characteristic"
```
I feel this should have been:
```json
                "$ref": "Characteristic.jsonschema#/definitions/ru.beeline.tmf.model.Characteristic"
```

**Comment by chrusty** [comment]
Hey @neopaf. Thanks for raising this, it seems that I need to spend some time investigating the `$ref` behaviour.

**Comment by chrusty** [comment]
Hey @neopaf.

I've been investigating your other issue with $refs, and in the process of that have been testing the generated schemas using https://www.jsonschemavalidator.net/. The format generated by the JSONSchema library i'm using seems to work fine in there. In any case, if it didn't work fine then I have a much bigger problem on my hands!

Granted, this will only work if all of the generated schemas are embedded in the "definitions" as you've mentioned, but hopefully I have something for you along those lines too. Let's switch to the other issue for now.

**Comment by neopaf** [comment]
(can't reopen myself, please consider)

I've checked https://www.jsonschemavalidator.net/, and indeed it properly marks this code as invalid:
```json
{
	"characteristic": [{"char_idB": "hi"}]
}
```
against `Party.jsonschema`.

Regretfully I've dug for an hour and can't find anything that allows such syntax as we have now :(

There is also a lot of talk in spec about non-canonical URI's and spec `$id` and resolutions but that is about separate files, not parts of one file.
And even
> it is RECOMMENDED that schema authors only use canonical URIs, as using non-canonical URIs may reduce schema interoperability

I've played a bit with [validator](https://www.jsonschemavalidator.net/) and see that any schemas, defined under `/definitions` or `/$defs` it treats as "known" and allows refs to them just by name.

I see nothing that allows this approach in specs. On the contrary, see explicit example from here
https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.8.2.4

```json
{
    "type": "array",
    "items": { "$ref": "#/$defs/positiveInteger" },
    "$defs": {
        "positiveInteger": {
```

Should such implicit resolution be possible they would have used `"$ref": "positiveIniteger"`, but they didn't.

**Comment by neopaf** [comment]
All in all, I feel, current `$ref` value should be changed to follow JSON Pointer format, as per spec chapter
https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.9.2
> 9.2. Dereferencing
> Schemas can be identified by any URI that has been given to them, including a JSON Pointer or their URI given directly by "$id"

We have no `$id` (and I wouldn't like going that way).
So we are left with JSON Pointer.

what we have now is not a JSON pointer.

As I understand your approach now, schemas are independent, so I change my suggestions to change
```json
                "$ref": "ru.beeline.tmf.model.Characteristic"
```
to 
```json
                "$ref": "#/definitions/ru.beeline.tmf.model.Characteristic"
```

That would make it a valid local JSON pointer, whould should be understood by all.

I've tested with [validator](https://www.jsonschemavalidator.net/)  and it was happy.

Please consider this change. Maybe optional?

**Comment by neopaf** [comment]
Probably I should give some background as to what I'm doing with these schemas.
I'm trying to work out some examples of usage of an interface, defined in `.proto` files.
Since I found no convenient ways to do that, I remembered that one can validate content against JSON Schema, and IntelliJ IDEA can do that extremely conveniently.

So I've started with an example and discovered that JSON validator in IntelliJ IDEA was not happy about our `$ref` values.

It just doesn't follow them :(

![image](https://user-images.githubusercontent.com/4362564/134297003-ae3c8bf7-9b04-4bd0-ab40-454a1609f4e9.png)


And hence doesn't validate my example documents against them properly.

**Comment by neopaf** [comment]
But after suggested change (global replace) it started to follow `$refs` to proper definitions and I became locally-happy:

![image](https://user-images.githubusercontent.com/4362564/134297178-1d868b3a-256e-4bb8-959d-e37ad748ea7b.png)

(I could add a hack that starts a global replace after your plugin, but I'm trying to avoid that uglines and go straight to you ;)

**Comment by chrusty** [comment]
OK I see. I'll keep this in mind when dealing with the other $ref issue. And yes, if it causes a problem then we can hide this behind a feature flag. Either way, you shouldn't have to do this global replace.

**Comment by neopaf** [comment]
Thanks for the attitude!
A bit of a quriosity: what do you use your plugin? What tasks did you aim it to?

**Comment by chrusty** [comment]
I don't even use this thing any more really... I WAS using it for some clients who were defining event payloads using protobuf, but wanted to be able to validate them against some kind of schema library. I guess it was done in a generic way, so it has been useful to other people.

By the way I've been testing the `#!/definitions` thing and it works with the online validator I use, but not with the Go library I use. So I think this one will have to be hidden with a feature flag.

**Comment by neopaf** [comment]
thanks a ton for your efforts!
(hope that doesn't distract you much from other affairs ;)

**Comment by chrusty** [comment]
It's OK, I like this project. At the moment none of my jobs involve writing
any GoLang, so these open-source projects allow me to keep my brain
occupied.

**Comment by chrusty** [comment]
@neopaf take a look at this PR: https://github.com/chrusty/protoc-gen-jsonschema/pull/86 - it allows you to provide a custom prefix for any $refs.

Please let me know if this is something that you would use. I would not make this the default behaviour, because the schemas generated by protoc-gen-jsonschema are intended to be fully self-contained within one file (all dependencies in one place). This means that references would never be to a separate file or location.

**Comment by neopaf** [comment]
thanks!
I'll check it out as I'll return from a small vacation.

**Comment by chrusty** [comment]
Actually I've brought this back into the other $ref PR: https://github.com/chrusty/protoc-gen-jsonschema/pull/82

**Comment by neopaf** [comment]
@chrusty , that PR looks very reasonable to me. Thanks a lot for these efforts!

**Comment by chrusty** [comment]
See the [new release](https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.2.0)

**Comment by neopaf** [comment]
oh. Christmas came earlier this year? :)

Thanks a lot!
(I expect other people being not so happy and asking you to make this optional ;)
