### ISSUE TITLE
Sometimes $ref, sometimes embed

### ISSUE THREAD

**Issue by neopaf** [chrusty/protoc-gen-jsonschema#74]
Source:
[model.proto.txt](https://github.com/chrusty/protoc-gen-jsonschema/files/7186350/model.proto.txt)

Why we don't get reference generated in 100% cases.
From `Party.jsonschema` -- `characteristic.items` is ref, while `external_id.items` is embedded.
```json
        "characteristic": {
            "items": {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "$ref": "ru.beeline.tmf.model.Characteristic"
        ....
        "external_id": {
            "items": {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "properties": {
                    "external_identification_type_id": {
```

I feel it should always be a ref.
currently `external_identification_type_id` field is generated in 5 files, while file `ExternalIdentification.jsonschema` is not referenced at all.

**Comment by neopaf** [comment]
My feeling is that Characteristics refers to itself, so it was "forced" into some separate "mode".
I feel that mode could be extended to all messages, resulting in `$ref`-s everywhere.

**Comment by chrusty** [comment]
This is interesting behaviour, I'll take a look and see if I can figure it out.

This referential logic is a bit mind-bending at times.

**Comment by chrusty** [comment]
Hello @neopaf, OK I have something for you to try out!

I've spent some time today trying to figure out what's going on here. The code used to generate references was contributed by someone else, so It did take me some time to familiarise myself with it. They had hard-coded a comparison that checks how many times a message is mentioned, and only creates a reference to a definition if it appears MORE THAN 1 time. This explains why `Characteristic` was being picked up: it was mentioned 4 times, whereas `external_id` was only mentioned 1 time.

I'm working on a new branch to fix this issue, and I think now would be a good time for you to give it a try and confirm that it does what you want (particularly in conjunction with the `messages=[Party]` option I mentioned in response to one of the other issues you raised).

https://github.com/chrusty/protoc-gen-jsonschema/tree/investigating_ref_behaviour

Once you've confirmed that this looks good, I will then need to fix up the unit tests. Also some of our users may consider this a breaking change, but we will find a way to deal with that later.

**Comment by neopaf** [comment]
thanks! (fantastic reaction speed!)

tested, I see that by default all schema files now contain `definitions`:
```json
{
    "$ref": "Characteristic",
    "definitions": {
        "Characteristic": {
```

And now all are referenced instead of embedded.
Which is a good!

I've tested `messages=[Party]:` option and found that it reverts root object to old approach, but still keeps all used type declaration separately and embeds nothing, which is also good.

I'm not 100% sure about if this behaviour should be a default or optional, totally up to you!


I'd prefer to discuss other issues separately not to mix things, would reopen what I'm still concerned about. Hope you'd not get offended!

**Comment by chrusty** [comment]
This has been merged and [released](https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.2.0)
