### ISSUE TITLE
Add custom option (similar to hidden) that lets user specify specific required fields

### ISSUE THREAD

**Issue by clementdoordash** [chrusty/protoc-gen-jsonschema#76]
Currently required is all or nothing for proto3 syntax. Would be really helpful to have a custom option that let's us specify if a single attirbute is required in json.
```
message RequiredFields {
    string not_required = 1 [(protoc.gen.jsonschema.required) = false];
    string required = 2 [(protoc.gen.jsonschema.required) = true];
    string default_not_required = 3; // by default proto3 is not required
}
```

**Comment by chrusty** [comment]
Hey @clementdoordash, thanks for raising this.

OK, I guess this means that you've already tried the new hidden / ignore option?

Implementing this "required" logic using another proto option shouldn't be too much of a hassle. I'll take a look and hopefully get something implemented for you to try soon.

**Comment by chrusty** [comment]
Have a look at the new release https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.0.5

Hopefully this does what you need!

**Comment by clementdoordash** [comment]
Yes! That's exactly it. Thank you :).

**Comment by chrusty** [comment]
I'm glad this is working as expected. Like I said, easy enough to implement.

I would like to point out that I have done this in quite a messy way, and have some [work in the pipeline](https://github.com/chrusty/protoc-gen-jsonschema/issues/79) to tidy up how these custom options are presented and interpreted. I've also [applied for an official options number in the protobuf repo](https://github.com/protocolbuffers/protobuf/pull/8999).

It means that in a future release you will have to use the protoc-gen-jsonschema options.proto in a slightly different way, but it shouldn't be a huge change for you. Just a heads up.

**Comment by chrusty** [comment]
OK, the new behaviour is live in https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.1.0
