### ISSUE TITLE
When specifying the disallow_bigints_as_strings, oneOf is still used instead of type

### ISSUE THREAD

**Issue by huttotw** [chrusty/protoc-gen-jsonschema#8]
I like the ability to have big ints in scientific notation as strings, however with the option turned on, the type could be `string` or `integer`, that makes sense.

I am proposing that when the option is turned off, meaning it can only be a `integer`, what we revert to using the `type` field in JSON schema to denote the `type` of the property.

For instance:
```json
"response_start": {
  "oneOf": [{
    "type": "integer"
  }]
},
```

should be
```json
"response_start": {
  "type": "integer"
}
```

**Comment by chrusty** [comment]
Hi @huttotw.

The PR recently merged should fix this up. Sorry it took so long!
