### ISSUE TITLE
Use .json, not .jsonschema for JSON schemas

### ISSUE THREAD

**Issue by grant** [chrusty/protoc-gen-jsonschema#88]
Tooling is generally better with the `.json` extension with JSON schemas, and the spec is indifferent with file extension. We should rename `.jsonschema` to `.json` everywhere in this repo.

I do not know/remember if this proposed change would just be internal or would be external.

**Comment by chrusty** [comment]
Hey @grant I've [opened a PR](https://github.com/chrusty/protoc-gen-jsonschema/pull/92) which allows the user to specify whatever file extention they like. Let me know if this works for you.

**Comment by grant** [comment]
Thanks! This is a great improvement.

I think we should also consider the default extension to be `.json` since this  is the the `application/json` MIME type and allow developers to use `.jsonschema` or other `.*` extensions.

There are a few links for this rationale. Example:
https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01#section-4.1

**Comment by chrusty** [comment]
I kinda liked calling them `jsonschema` because it's a specific usage of JSON, but whatever, long as people can use the option to override it then we haven't _removed_ the original behaviour, right.

**Comment by grant** [comment]
I've always thought the file format is really just JSON and should be parsed/treated as JSON but with the special `$schema` field as the indicator of if the JSON document is a schema document or something else.

Either way, the option for developers works for me!

**Comment by chrusty** [comment]
https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/1.2.3
